#!/bin/sh

IDE=/disk/disk.ide

if [ ! -e $IDE ]; then
    # 1 = 504MB IDE disk
    # 5 = 128MB IDE disk
    makedisk 5 $IDE

    #dd bs=1024 if=/disk/hd1k_combo.img of=$IDE conv=notrunc seek=1

    # If building our own dive image, we'll need to use these commands instead
    # Disk partition table
    dd bs=1024 if=/disk/hd1k_prefix.dat of=$IDE conv=notrunc seek=1
    # ZSDOS
    SLICE=0
    dd bs=1024 if=/disk/hd1k_zsdos.img of=$IDE conv=notrunc seek=$((1024*8*$SLICE + 1024 + 1))
    # Turbo Pascal
    SLICE=1
    dd bs=1024 if=/disk/hd1k_tpascal.img of=$IDE conv=notrunc seek=$((1024*8*$SLICE + 1024 + 1))
    # Games
    SLICE=2
    dd bs=1024 if=/disk/hd1k_games.img of=$IDE conv=notrunc seek=$((1024*8*$SLICE + 1024 + 1))
    # Games
    SLICE=3
    dd bs=1024 if=/disk/hd1k_aztecc.img of=$IDE conv=notrunc seek=$((1024*8*$SLICE + 1024 + 1))
fi

exec rc2014 -a -w -R -b -r /rom/RCZ80_std.rom -i /disk/disk.ide
